npcs:
  Lia: "citizens 0"
npc_conversations:
  Lia: Lia
items:
  daisy: "simple oxeye_daisy"
  dandelion: "simple dandelion"
  bread: "simple bread"
  healing_potion: simple potion "type:HEALING" "upgraded:true"